#!/bin/sh
# Contacto elroberasis@gmail.com
# Este  bash actua informando cuando una MAC está cerca del alcance de una antena puesta en modo monitor
# esta(s) MAC, a buscar,  las podemos tener en un archivo.
# Así, tambien es la idea capturar los Probe-request generados y aumentar la información decaptura
# chmod +x script (para poder ejecutar)
# paplay (audio) ogg
######################################
clear


asd() {
cat <<"EOT"
                                _                 _
 _ __ ___   __ _  ___          | |__  _   _ _ __ | |_ ___ _ __
| '_ ` _ \ / _` |/ __|  _____  | '_ \| | | | '_ \| __/ _ \ '__|
| | | | | | (_| | (__  |_____| | | | | |_| | | | | ||  __/ |
|_| |_| |_|\__,_|\___|         |_| |_|\__,_|_| |_|\__\___|_| 

 V 1.3     By jmv17

EOT
}
asd

sleep 1
####### declaracion funcion comparacion
comparacion(){
clear
asd
echo "============================="
echo " introduce ruta del archivo 1"
echo "-----------------------------"
read varcomparacion1
echo "============================="
echo " introduce ruta del archivo 2"
echo "-----------------------------"
read varcomparacion2
echo -n "nombre del archivo resultante: "
read resultante
fgrep -f $varcomparacion1 $varcomparacion2 > /root/Desktop/$resultante$csv
csv=".csv"
cat /root/Desktop/$resultante

}






######## declaracion funcion HUNTER
caza(){

#########  AQUI LAS RUTAS DE ARCHIVOS  ####################
###########################################################

varruta="/root/Desktop/mac_hunter/" # ruta donde dejar el archivo de capturas 
varrutaaudio="/root/Desktop/mac_hunter/ogg/audio1.ogg" #ruta del archivo audio ogg
var1="/root/Desktop/mac_hunter/macs"  #ruta donde  poner el archivo con las MACs a cazar

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
csv="-01.csv" #salida de archivo airodump-ng
###########################################################
clear
asd
echo "=========== conectado a...============================"

iwgetid
echo "======================================================"

echo
echo "HUNTER  MODE ON....!!!"
echo
echo  "\033[32mLISTA DE INTERFACES" \

sudo airmon-ng

echo "introduce una \"Interface\" para monitor mode"
read varmonitor
sudo airmon-ng start $varmonitor
clear
ifconfig -s
echo
echo "escribe el nombre del Iface en modo monitor"
read varmonitorok
clear
echo "======================================================"
echo "introduce un nombre, para el archivo de capturas MAC"
echo "======================================================"  
#pwd
echo
read varnombre
#gnome-terminal -e "airodump-ng  $varmonitorok --output- csv -w $varruta" #esto lanza otro terminal
#con el airodump-ng, con nohub esta oculto  
sudo nohup airodump-ng $varmonitorok --output- csv -w $varruta$varnombre &
sleep 2
#egrep "$varmac" $var2
clear
# La -f de grep es para  buscar fichero de patrones
#grep -f "$var1" $varnueva
################################
asd2() {
cat <<"EOT"
  _                 _   _
 | |               | | (_)
 | |__  _   _ _ __ | |_ _ _ __   __ _
 | '_ \| | | | '_ \| __| | '_ \ / _` |
 | | | | |_| | | | | |_| | | | | (_| |
 |_| |_|\__,_|_| |_|\__|_|_| |_|\__, |
                                 __/ |
                                |___/






EOT
}
asd2
#########################


while ! grep -f "$var1" $varruta$varnombre$csv 
do
grep -f "$var1" $varruta$varnombre$csv  
done
clear
###############
asd3() {
cat <<"EOT"
         _                 _           _
        | |__  _   _ _ __ | |_ ___  __| |
 _____  | '_ \| | | | '_ \| __/ _ \/ _` |  _____
|_____| | | | | |_| | | | | ||  __/ (_| | |_____|
        |_| |_|\__,_|_| |_|\__\___|\__,_|

 ================
 MAC capturadas..
 ================


EOT
}
asd3

####### audio #########
paplay  $varrutaaudio 
#######################
echo "Mostrar captura...(si/no)"
read seguir
 if [ "$seguir" = "si" ] 
	then
while ! grep -f "$var1" $varruta$varnombre$csv 
do
grep -f "$var1" $varruta$varnombre$csv
done
awk '/$var1/ { print $1, $8, $9, $10 }' $varruta$varnombre$csv ###
sudo airmon-ng stop $varmonitorok
echo
echo "===================================="
echo "       modo monitor parado ...      "
echo "===================================="
echo
###
else
clear

#######################################

#############################
sudo airmon-ng stop $varmonitorok
clear
echo
echo "===================================="
echo "       modo monitor parado ...      "
echo "===================================="
echo
fi

}


####MENU#####
echo "********************************"
echo "elije la opcion, 1 ó 2, del menu:"
echo "********************************"
echo
echo "-1- Esta opción compara 2 archivos y muestra la(s) Mac(s) coincidente, genera 1 archivo"
echo ""
echo "-2- Esta opcion entra en modo CAZA ACTIVA hasta encontrar la(s) Mac(s) solicitadas"
echo ""
echo "******************************************************************************************"
read character
if [ "$character" = "1" ]; then
comparacion

else
if [ "$character" = "2" ]; then
caza

else
if [ "$character" = "3" ]; then
echo "has elejido 3"
else
echo "no has elejido opcion, por defecto MAC-HUNTER"
fi
fi
fi
